package Juju::Manual::Quickstart;

=head1 INSTALL

Installation is handled through cpanm and you can point directly to
the github repository:

    cpanm git@github.com:battlemidget/perl-juju.git

=head1 INTRO

The library exposes juju rpc interface via a secure
websocket. The credentials required are found in your
B<~/.juju/environments/'env'.jenv>. If that directory/file does not
exist you'll want to make sure you've bootstrapped first:

    juju bootstrap --upload-tools

See more information on the workings of juju at
L<http://juju.ubuntu.com>

=head1 USING

To get started initialize the Juju class:

    use Juju;

    # Open connection over the websocket protocol
    my $juju = Juju->new(endpoint => 'wss://192.168.122.16:17070', password => '8fdsaf0fda');
    $juju->login;
    my $juju_info = $juju->info;
    print $juju_info->{UUID};

    # Close the connection
    $juju->close;

The password is found in the B<~/.juju/environments/'env'.jenv> under
C<admin-secret>.

There is a B<port (17070)> for accessing the machine resources.

=cut

1;
