---
language: perl
perl:
  - '5.14'
  - '5.18'
  - '5.20'
notifications:
  email: false
install:
  - cpanm --notest -q --mirror-only --installdeps .
  - perl Makefile.PL
  - make
  - make install
script:
  - prove -r t
