---
abstract: 'Perl bindings for Juju'
author:
  - 'Adam Stokes <adamjs@cpan.org>'
build_requires:
  DDP: '0'
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  FindBin: '0'
  IO::Handle: '0'
  IO::Socket::SSL: '0'
  IPC::Open3: '0'
  Pod::Elemental::Transformer::List: '0'
  Pod::Weaver::Plugin::Encoding: '0'
  Pod::Weaver::Section::SeeAlso: '0'
  Test::Compile: '0'
  Test::Exception: '0'
  Test::Kwalitee: '0'
  Test::More: '0'
  Test::NoTabs: '0'
  lib: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.021, CPAN::Meta::Converter version 2.142690'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Juju
requires:
  AnyEvent: '0'
  AnyEvent::WebSocket::Client: '0'
  Function::Parameters: '0'
  HTTP::Tiny: '0'
  JSON::PP: '0'
  Moose: '0'
  Moose::Role: '0'
  Throwable::Error: '0'
  YAML::Tiny: '0'
  namespace::autoclean: '0'
resources:
  homepage: https://github.com/battlemidget/p5-juju
  repository: https://github.com/battlemidget/p5-juju.git
version: '2.002'
x_authority: cpan:ADAMJS
