---
abstract: 'Non-blocking Perl bindings for http://juju.ubuntu.com/'
author:
  - 'Adam Stokes <adamjs@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IO::Socket::SSL: '0'
  IPC::Open3: '0'
  Pod::Elemental::Transformer::List: '0'
  Pod::Weaver::Plugin::Encoding: '0'
  Test::Compile: '0'
  Test::Kwalitee: '0'
  Test::More: '0'
  Test::NoTabs: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142690'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Juju
requires:
  AnyEvent: '0'
  AnyEvent::WebSocket::Client: '0'
  Class::Tiny: '0'
  JSON::PP: '0'
  parent: '0'
  strict: '0'
  warnings: '0'
resources:
  repository: git://github.com/battlemidget/p5-juju
version: '0.8'
